openapi: 3.0.3

info:
  title: School API
  version: "1.0"

servers:
  - url: http://localhost/api/v1

tags:
  - name: Education Level
    description: Módulo de niveles educativos
  - name: Subject
    description: Módulo de asignaturas
  - name: Teacher
    description: Módulo de docentes

paths:
  /levels:
    get:
      tags:
        - Education Level
      summary: Listar niveles
      operationId: level.list
      responses:
        "200":
          $ref: "#/components/responses/ListLevelResponse"

  /subjects:
    get:
      tags:
        - Subject
      summary: Listar asignaturas
      operationId: subject.list
      parameters:
        - name: per_page
          in: query
          description: Cantidad de registros por página
          schema:
            type: string
            nullable: true
        - name: search
          in: query
          description: Texto de búsqueda
          schema:
            type: string
            nullable: true
      responses:
        "200":
          $ref: "#/components/responses/ListSubjectResponse"

    post:
      tags:
        - Subject
      summary: Crear asignatura
      operationId: subject.create
      requestBody:
        $ref: "#/components/requestBodies/CreateSubjectRequest"
      responses:
        "201":
          description: Asignatura creada
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Subject"
        "422":
          description: Errores de validacion

  /subjects/{id}:
    get:
      tags:
        - Subject
      summary: Mostrar asignatura
      operationId: subject.show
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            description: ID de asignatura
      responses:
        "200":
          description: Asignatura editada
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Subject"
        "404":
          description: Asignatura no encontrada

    put:
      tags:
        - Subject
      summary: Editar asignatura
      operationId: subject.edit
      requestBody:
        $ref: "#/components/requestBodies/EditSubjectRequest"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            description: ID de asignatura
      responses:
        "200":
          description: Asignatura editada
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Subject"
        "404":
          description: Asignatura no encontrada
        "422":
          description: Errores de validacion

    delete:
      tags:
        - Subject
      summary: Eliminar asignatura
      operationId: subject.delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            description: ID de asignatura
      responses:
        "200":
          $ref: "#/components/responses/DeleteResponse"
        "404":
          description: Asignatura no encontrada

  /subjects/{id}/active:
    patch:
      tags:
        - Subject
      summary: Activar asignatura
      operationId: subject.active
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            description: ID de asignatura
      requestBody:
        $ref: "#/components/requestBodies/ChangeActiveSubjectRequest"
      responses:
        "200":
          description: Asignatura editada
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Subject"
        "404":
          description: Asignatura no encontrada

  /sublevels:
    get:
      tags:
        - Education Level
      summary: Listar subniveles (grados)
      operationId: sublevel.list
      responses:
        "200":
          $ref: "#/components/responses/ListSublevelResponse"

  /teachers:
    get:
      tags:
        - Teacher
      summary: Listar docentes
      operationId: teacher.list
      parameters:
        - name: per_page
          in: query
          description: Cantidad de registros por página
          schema:
            type: string
            nullable: true
        - name: search
          in: query
          description: Texto de búsqueda
          schema:
            type: string
            nullable: true
      responses:
        "200":
          $ref: "#/components/responses/ListTeacherResponse"

    post:
      tags:
        - Teacher
      summary: Registrar docente
      operationId: teacher.create
      requestBody:
        $ref: "#/components/requestBodies/CreateTeacherRequest"
      responses:
        "201":
          description: Docente registrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Teacher"
        "422":
          description: Errores de validacion

  /teachers/{id}:
    get:
      tags:
        - Teacher
      summary: Mostrar docente
      operationId: teacher.show
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            description: ID de docente
      responses:
        "200":
          description: Docente encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Teacher"
        "404":
          description: Docente no encontrado

    put:
      tags:
        - Teacher
      summary: Editar docente
      operationId: teacher.edit
      requestBody:
        $ref: "#/components/requestBodies/EditTeacherRequest"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            description: ID de docente
      responses:
        "200":
          description: Datos de docente modificados
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Teacher"
        "404":
          description: Docente no encontrado
        "422":
          description: Errores de validacion

    delete:
      tags:
        - Teacher
      summary: Eliminar docente
      operationId: teacher.delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            description: ID de docente
      responses:
        "200":
          $ref: "#/components/responses/DeleteResponse"
        "404":
          description: Docente no encontrado

components:
  schemas:
    Level:
      type: object
      properties:
        code:
          type: string
          description: Código usado para identificar el nivel
        name:
          type: string
          description: Nombre del nivel

    Subject:
      type: object
      properties:
        ode:
          type: string
          description: Código usado para identificar la asignatura
        name:
          type: string
          description: Nombre de la asignatura
        active:
          type: boolean
          description: Indica si esta activo o no

    Sublevel:
      type: object
      properties:
        code:
          type: string
          description: Código usado para identificar el grado
        name:
          type: string
          description: Nombre del grado
        level:
          $ref: "#/components/schemas/Level"

    Teacher:
      type: object
      properties:
        id:
          type: integer
          description: ID de docente
        first_name:
          type: string
          description: Nombres del docente
          example: Carlos
        last_name:
          type: string
          description: Apellidos del docente
          example: Diaz Riveros
        email:
          type: string
          description: Correo electrónico del docente
          example: cdiaz@gmail.com
        phone:
          type: string
          description: Número telefónico del docente
          example: +5193554112
        address:
          type: string
          description: Dirección del docente
          example: Calle Perú 345
        created_at:
          type: string
          format: date-time
          description: Fecha de registro

  requestBodies:
    ChangeActiveSubjectRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - active
            properties:
              active:
                type: boolean
                description: Indica si estará activo o no la asignatura

    CreateSubjectRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - code
            properties:
              name:
                type: string
                description: Nombre de la asignatura
                example: "Geografía"
              code:
                type: string
                description: Código de la asignatura
                example: "GEO"

    CreateTeacherRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - first_name
              - last_name
              - email
              - phone
              - address
            properties:
              first_name:
                type: string
                description: Nombres del abogado
                example: Carlos Alberto
              last_name:
                type: string
                description: Apellidos del abogado
                example: Perez Ruiz
              email:
                type: string
                description: Correo electrónico del docente
                example: cdiaz@gmail.com
              phone:
                type: string
                description: Número telefónico del docente
                example: +5193554112
              address:
                type: string
                description: Dirección del docente
                example: Calle Perú 345

    EditSubjectRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - code
            properties:
              name:
                type: string
                description: Nombre de la asignatura
                example: "Geografía"
              code:
                type: string
                description: Código de la asignatura
                example: "GEO"

    EditTeacherRequest:
      content:
        application/json:
          schema:
            type: object
            required:
              - first_name
              - last_name
              - email
              - phone
              - address
            properties:
              first_name:
                type: string
                description: Nombres del abogado
                example: Carlos Alberto
              last_name:
                type: string
                description: Apellidos del abogado
                example: Perez Ruiz
              email:
                type: string
                description: Correo electrónico del docente
                example: cdiaz@gmail.com
              phone:
                type: string
                description: Número telefónico del docente
                example: +5193554112
              address:
                type: string
                description: Dirección del docente
                example: Calle Perú 345

  responses:
    DeleteResponse:
      description: Registro eliminado
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                description: ID del registro
              deleted:
                type: boolean
                default: true
                description: Indica que el registro fue eliminado

    ListLevelResponse:
      description: Mostrar niveles
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/components/schemas/Level"

    ListSubjectResponse:
      description: Mostrar subniveles
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/components/schemas/Subject"

    ListSublevelResponse:
      description: Mostrar subniveles
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/components/schemas/Sublevel"

    ListTeacherResponse:
      description: Mostrar docentes
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/components/schemas/Teacher"
